DROP TABLE IF EXISTS twentyonetable;
CREATE TABLE twentyonetable (
  year real,
  yearend real,
  locationabbr text,
  locationdesc text,
  datasource text,
  topic text,
  question text,
  datavalueunit text,
  datavaluetype text,
  datavalue real, 
  datavaluealt real,
  datavaluefootnotesymbol text,
  datavaluefootnote text,
  lowconfidencelimit real,
  highconfidencelimit real, 
  stratificationcategory1 text,
  stratification1 text,
  locationid real, 
  topicid text,
  questionid text,
  datavaluetypeid text,
  stratificationcategoryid1 text,
  stratificationid1 text
  );